version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ecommerce
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: .
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/db_ecommerce
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
    ports:
      - "8080:8081"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: