version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  product-service:
    build: .
    container_name: product-service
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: