spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: DEBUG
    com.ecommerce.product_service: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/application.log

jwt:
  secret-key: VmvrnN3KhH+fT2UsmP3BcJMDEWig/1MA1T76PC1wxLw=
  token-validity: 3600000