spring:
  main:
    web-application-type: reactive  # Esto configura tu aplicación como reactiva
  r2dbc:
#    url: ${SPRING_R2DBC_URL:r2dbc:mysql://mysql.railway.internal:31700/railway}
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/db_ecommerce}
    username: ${SPRING_R2DBC_USERNAME:root}
#    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}
#    password: ${SPRING_R2DBC_PASSWORD:arIdTuREYHdwATEjqJsVFMOAdqizhhva}
  sql:
    init:
#      mode: always
      mode: never
      schema-locations: classpath:schema.sql
  webflux:
    base-path: /api
  jackson:
    time-zone: America/Bogota

server:
  port: 8080

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: DEBUG
    com.ecommerce.product_service: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/application.log

jwt:
  secret-key: VmvrnN3KhH+fT2UsmP3BcJMDEWig/1MA1T76PC1wxLw=
  token-validity: 3600000