spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/db_ecommerce}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080

logging:
  level:
    org.springframework.data.r2dbc: DEBUG