spring:
  main:
    web-application-type: reactive  # Esto configura tu aplicación como reactiva
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}}
#    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/db_ecommerce}
#    username: ${SPRING_R2DBC_USERNAME:root}
    username: ${SPRING_R2DBC_USERNAME:${DB_USER}}
#    password: ${SPRING_R2DBC_PASSWORD:root}
    password: ${SPRING_R2DBC_PASSWORD:${DB_PASSWORD}}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: DEBUG
    com.ecommerce.product_service: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/application.log

jwt:
  secret-key: VmvrnN3KhH+fT2UsmP3BcJMDEWig/1MA1T76PC1wxLw=
  token-validity: 3600000