spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/db_product
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080

logging:
  level:
    org.springframework.data.r2dbc: DEBUG